/**
 * Infrastructure Analytics & Insights Endpoint
 * GET /api/infrastructure/analytics
 */

import { NextRequest, NextResponse } from 'next/server'
import {
  getMetricsSnapshot,
  getDomainAnalytics,
  generateRecommendations,
  analyzePerformancePatterns,
} from '@/lib/infrastructure-analytics'

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams
    const format = searchParams.get('format') || 'json' // json | report

    const [metrics, domains, recommendations, performance] = await Promise.all([
      getMetricsSnapshot(),
      getDomainAnalytics(),
      generateRecommendations(),
      analyzePerformancePatterns(),
    ])

    if (format === 'report') {
      // Return text report format
      const report = `
# Infrastructure Analytics Report
Generated: ${new Date().toISOString()}

## System Metrics
- Total Domains: ${metrics.domainCount}
- Healthy Domains: ${metrics.healthyDomains}
- Total Inboxes: ${metrics.inboxCount}
- Total Capacity: ${metrics.totalCapacity} emails/day
- Current Utilization: ${Math.round(metrics.capacityUtilization)}%
- Emails Sent (24h): ${metrics.emailsSent24h}
- Uptime: ${metrics.uptime.toFixed(1)}%

## Email Delivery Metrics
- Average Bounce Rate: ${(metrics.averageBounceRate * 100).toFixed(3)}%
- Average Spam Rate: ${(metrics.averageSpamRate * 100).toFixed(3)}%
- Average Delivery Time: ${metrics.avgDeliveryTime.toFixed(2)}s

## Domain Health Breakdown
${domains
  .map(
    (d) => `
### ${d.domain}
- Status: ${d.paused ? 'PAUSED' : d.health.toUpperCase()}
- Health Score: ${d.health}
- Inboxes: ${d.inboxCount}
- Emails Sent (24h): ${d.emailsSent24h}
- Bounce Rate: ${(d.bounceRate * 100).toFixed(3)}%
- Spam Rate: ${(d.spamRate * 100).toFixed(3)}%
- Avg Delivery Time: ${d.avgDeliveryTime.toFixed(2)}s
`
  )
  .join('\n')}

## Performance Analysis
- Peak Hour: ${performance.peakHour}:00 UTC
- Average Hourly Load: ${performance.avgLoad} emails
- Maximum Hourly Load: ${performance.maxLoad} emails
- Load Factor: ${((performance.maxLoad / performance.avgLoad) * 100 - 100).toFixed(0)}% above average

${performance.bottlenecks.length > 0 ? `### Bottlenecks\n${performance.bottlenecks.map((b) => `- ${b}`).join('\n')}\n` : ''}

### Insights
${performance.insights.map((i) => `- ${i}`).join('\n')}

## Actionable Recommendations
${recommendations
  .map(
    (r, i) => `
### ${i + 1}. ${r.title} [${r.priority.toUpperCase()}] (${Math.round(r.confidence * 100)}% confidence)
**Category:** ${r.category}

**Description:** ${r.description}

**Recommended Action:** ${r.action}

**Expected Impact:** ${r.estimatedImpact}
`
  )
  .join('\n')}

## Performance Trends
- System is ${metrics.capacityUtilization > 90 ? 'critically' : metrics.capacityUtilization > 75 ? 'highly' : 'normally'} utilized
- Domain health is ${metrics.healthyDomains / metrics.domainCount > 0.8 ? 'excellent' : metrics.healthyDomains / metrics.domainCount > 0.5 ? 'good' : 'concerning'}
- Deliverability metrics are ${metrics.averageBounceRate < 0.03 ? 'healthy' : 'need attention'}

---
Report generated by Infrastructure Analytics System
`

      return new Response(report, {
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'Content-Disposition': 'attachment; filename="infrastructure-analytics.txt"',
        },
      })
    }

    // Default JSON format
    return NextResponse.json({
      timestamp: new Date().toISOString(),
      metrics: {
        domains: metrics.domainCount,
        healthyDomains: metrics.healthyDomains,
        inboxes: metrics.inboxCount,
        capacity: {
          total: metrics.totalCapacity,
          used: metrics.usedCapacity,
          utilization: Math.round(metrics.capacityUtilization),
        },
        emails: {
          sent24h: metrics.emailsSent24h,
          avgDeliveryTime: Math.round(metrics.avgDeliveryTime * 1000) / 1000,
        },
        health: {
          uptime: Math.round(metrics.uptime * 10) / 10,
          avgBounceRate: Math.round(metrics.averageBounceRate * 10000) / 100,
          avgSpamRate: Math.round(metrics.averageSpamRate * 10000) / 100,
        },
      },
      domains: domains
        .sort((a, b) => b.emailsSent24h - a.emailsSent24h)
        .map((d) => ({
          id: d.domainId,
          domain: d.domain,
          health: d.health,
          paused: d.paused,
          inboxes: d.inboxCount,
          sent24h: d.emailsSent24h,
          bounceRate: Math.round(d.bounceRate * 10000) / 100,
          spamRate: Math.round(d.spamRate * 10000) / 100,
          avgDeliveryTime: Math.round(d.avgDeliveryTime * 1000) / 1000,
        })),
      performance: {
        peakHour: performance.peakHour,
        avgLoad: performance.avgLoad,
        maxLoad: performance.maxLoad,
        bottlenecks: performance.bottlenecks,
        insights: performance.insights,
      },
      recommendations: recommendations.map((r) => ({
        id: r.id,
        category: r.category,
        priority: r.priority,
        title: r.title,
        description: r.description,
        action: r.action,
        estimatedImpact: r.estimatedImpact,
        confidence: Math.round(r.confidence * 100),
      })),
    })
  } catch (error) {
    console.error('[API] Analytics error:', error)
    // Schema-compatible fallback (prevents UI parse failures).
    return NextResponse.json({
      timestamp: new Date().toISOString(),
      metrics: {
        domains: 0,
        healthyDomains: 0,
        inboxes: 0,
        capacity: { total: 0, used: 0, utilization: 0 },
        emails: { sent24h: 0, avgDeliveryTime: 0 },
        health: { uptime: 0, avgBounceRate: 0, avgSpamRate: 0 },
      },
      domains: [],
      recommendations: [],
      error: 'Analytics failed',
      details: String(error),
    })
  }
}
