import { NextResponse } from 'next/server'
import { query } from '@/lib/db'
import { resolveClientId } from '@/lib/client-context'
import type { NextRequest } from 'next/server'

export async function GET(request: NextRequest) {
  const clientId = await resolveClientId({ headers: request.headers })
  const matchedReplyWhere =
    `client_id = $1
     AND event_type = 'reply'
     AND COALESCE(metadata->>'matched_to_outbound', 'false') = 'true'
     AND COALESCE(metadata->>'is_auto_response', 'false') <> 'true'
     AND LOWER(
       COALESCE(metadata->>'subject', '') || ' ' ||
       COALESCE(metadata->>'body', '') || ' ' ||
       COALESCE(metadata->>'body_text', '')
     ) NOT LIKE ANY (ARRAY[
       '%auto-generated email%',
       '%autogenerated email%',
       '%automated email%',
       '%automatic reply%',
       '%out of office%',
       '%ticket no%',
       '%ticket number%',
       '%thanks for writing to us%',
       '%we will get back to you within%',
       '%do not reply%'
     ])`

  // Minimal proof endpoint: recent replies + rollups.
  const total = await query<{ count: string }>(
    `SELECT COUNT(*)::text AS count
     FROM events
     WHERE ${matchedReplyWhere}`,
    [clientId]
  )

  const perCampaign = await query<{ campaign_id: number | null; count: string }>(
    `SELECT campaign_id, COUNT(*)::text AS count
     FROM events
     WHERE ${matchedReplyWhere}
     GROUP BY campaign_id
     ORDER BY COUNT(*) DESC
     LIMIT 20`,
    [clientId]
  )

  const recent = await query<{
    id: number
    created_at: string
    campaign_id: number | null
    queue_job_id: number | null
    metadata: any
  }>(
    `SELECT id, created_at, campaign_id, queue_job_id, metadata
     FROM events
     WHERE ${matchedReplyWhere}
     ORDER BY created_at DESC
     LIMIT 50`,
    [clientId]
  )

  return NextResponse.json({
    total_replies: Number(total.rows[0]?.count ?? 0),
    replies_per_campaign: perCampaign.rows.map((r) => ({
      campaign_id: r.campaign_id,
      count: Number(r.count ?? 0),
    })),
    recent: recent.rows.map((r) => ({
      id: r.id,
      created_at: r.created_at,
      campaign_id: r.campaign_id,
      queue_job_id: r.queue_job_id,
      from_email: r.metadata?.from_email ?? null,
      to_email: r.metadata?.to_email ?? null,
      subject: r.metadata?.subject ?? null,
      body: r.metadata?.body ?? null,
      source: r.metadata?.source ?? null,
    })),
  })
}
